name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_PROVIDER: sqlite
      DATABASE_URL: file:./dev.db
      AUTH_SECRET: test-secret
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm install
      - run: npx prisma generate
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
      - name: Prisma schema diff
        run: npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --shadow-database-url file:./tmp.db
